# Generated by Django 3.0.1 on 2020-04-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_auto_20200407_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leader',
            old_name='name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='leader',
            name='score',
            field=models.IntegerField(null=True),
        ),
    ]
